// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUdNHtb60UIvYLjSt-E7D1IVr7MkhrDY',
    appId: '1:1075481159590:web:deb2b9f787f9ef14d0d167',
    messagingSenderId: '1075481159590',
    projectId: 'sporty-5bb17',
    authDomain: 'sporty-5bb17.firebaseapp.com',
    storageBucket: 'sporty-5bb17.appspot.com',
    measurementId: 'G-KPP64K48L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVzQA4GCrgksvdhj4L7QzD-DhH5kxAYRM',
    appId: '1:1075481159590:android:8c5a501c7c0f40ddd0d167',
    messagingSenderId: '1075481159590',
    projectId: 'sporty-5bb17',
    storageBucket: 'sporty-5bb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiKR5ldc6XYMHp4mdQQF-uY-GXeVEC3Qo',
    appId: '1:1075481159590:ios:c6807c0c9b0f3fdad0d167',
    messagingSenderId: '1075481159590',
    projectId: 'sporty-5bb17',
    storageBucket: 'sporty-5bb17.appspot.com',
    iosClientId: '1075481159590-3a83pst699kavlcjimgvi7lpqbicrdj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sporty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiKR5ldc6XYMHp4mdQQF-uY-GXeVEC3Qo',
    appId: '1:1075481159590:ios:c6807c0c9b0f3fdad0d167',
    messagingSenderId: '1075481159590',
    projectId: 'sporty-5bb17',
    storageBucket: 'sporty-5bb17.appspot.com',
    iosClientId: '1075481159590-3a83pst699kavlcjimgvi7lpqbicrdj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sporty',
  );
}
