// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4xOjqXocZlQjSBGb-aAbGjDPbo7d2wQ',
    appId: '1:555107589651:web:57e2a6881a707194d569e6',
    messagingSenderId: '555107589651',
    projectId: 'sporty-e7c07',
    authDomain: 'sporty-e7c07.firebaseapp.com',
    storageBucket: 'sporty-e7c07.appspot.com',
    measurementId: 'G-N301VBKTX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbksEXLRfeWRXhOQSqFUN63p6PH_LnJjU',
    appId: '1:555107589651:android:cfc3978a724cdfd2d569e6',
    messagingSenderId: '555107589651',
    projectId: 'sporty-e7c07',
    storageBucket: 'sporty-e7c07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-5iQbYYnavOd2nV7rsH54ZiL3TllmYbY',
    appId: '1:555107589651:ios:1f25a8631106b361d569e6',
    messagingSenderId: '555107589651',
    projectId: 'sporty-e7c07',
    storageBucket: 'sporty-e7c07.appspot.com',
    androidClientId: '555107589651-jofh5eo3is4pj37gqc4fj1fa31mgnees.apps.googleusercontent.com',
    iosClientId: '555107589651-rnddhn2fch6jfrmemlsm1toaapvc7u3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.sporty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-5iQbYYnavOd2nV7rsH54ZiL3TllmYbY',
    appId: '1:555107589651:ios:1f25a8631106b361d569e6',
    messagingSenderId: '555107589651',
    projectId: 'sporty-e7c07',
    storageBucket: 'sporty-e7c07.appspot.com',
    androidClientId: '555107589651-jofh5eo3is4pj37gqc4fj1fa31mgnees.apps.googleusercontent.com',
    iosClientId: '555107589651-rnddhn2fch6jfrmemlsm1toaapvc7u3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.sporty',
  );
}
